dogbook/urls.py
from django.contrib import admin
from django.urls import path, include
from dogbook import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dogbook' # namespace

# <int>: 숫자 하나 들어올거야~
# question_id: 변수 하나 잡아주는 것 -> views.detail에 전달이 된다
urlpatterns = [
    path('register/', views.register, name='register'),
    path('create_process/', views.create_process, name='create_process'),
    path('register/popup/', views.open_popup, name='popup'),
    path('register/popup/<str:username>', views.open_popup2, name='popup'),
    path('register/popup/idcheck/', views.id_check, name='id_check'),
    path('login/', views.login, name='login'),
    path('pet_register/', views.pet_register, name='pet_register'),
    path('missing/', views.missing, name='missing'),
    path('<str:username>/upload/', views.upload_page, name='upload_page'),
    path('uploading', views.upload, name='uploading'),
    path('<str:username>/', views.profile, name='profile'),


    # path('id_check/', views.request_page, name='id_check')
    # path('<int:question_id>', views.detail, name = 'detail')
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('<int:question_id>/results/', views.results, name='results')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dogstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from dogbook import views

# client의 URL을 얘가 먼저 받음
# http://localhost:8000/polls/ -> 'polls/'
# 이 URLConf는 설정임 여기서 실행시키는게 아님
# views.index는 polls로 들어오면 index()함수를 쓸거라고 알려주는 것
# view.index() 괄호 절대 쓰면 안돼!!

urlpatterns = [
    # path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('dogbook/', include('dogbook.urls'))
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dogbook/models.py
from django.db import models


# Create your models here.
class users(models.Model):
    # id INT, AUTO_INCREMENT NOT NULL PK 이거는 자동으로 만들어짐
    username = models.CharField(max_length=20, unique=True)
    full_name = models.CharField(max_length=20, blank=False)
    email = models.CharField(max_length=50)
    passwd = models.CharField(max_length=20)
    phoneno = models.CharField(max_length=15, blank=True)
    # FK 설정
    # on_delete = models.CASCADE 하면 혹시나 FK가 지칭하는거 지워지면 항목도
    # 지워지게 설정
    # columnname = models.ForeignKey(Classname, condition)

    def __str__(self):
        return self.username


class Image(models.Model):
    author = models.CharField(max_length=20, default='hello')
    name = models.CharField(max_length=500)
    imagefile = models.FileField(upload_to='images/', null=True, verbose_name="")
    upload_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + ": " + str(self.imagefile)


class Uploads(models.Model):
    author = models.CharField(max_length=20)
    content = models.CharField(max_length=500)
    imagefile = models.FileField(upload_to='images/')
    upload_date = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.content + ": " + str(self.imagefile)


class Uploads2(models.Model):
    author = models.CharField(max_length=20)
    content = models.CharField(max_length=500)
    imagefile = models.ImageField(upload_to='images/', blank=True, max_length=200)
    upload_date = models.DateTimeField(auto_now=True)

dogbook/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from dogbook.models import users, Image, Uploads, Uploads2
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
import pymysql
from dogbook import models


def index(request):
    return render(request, 'index.html')


def register(request):
    return render(request, 'dogbook/register.html')


def create_process(request):
    new_user = request.POST.get('username')
    con = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='wlgus7921', db='dogstagram_db', charset='utf8')
    cursor = con.cursor(pymysql.cursors.DictCursor)
    stmt = "SELECT username FROM dogbook_users WHERE username='{}'"
    stmt = stmt.format(new_user)
    cursor.execute(stmt)
    data = cursor.fetchall()

    if not data:
        user = users()
        user.username = request.POST.get('username')
        user.full_name = request.POST.get('full_name')
        user.email = request.POST.get('email')
        user.passwd = request.POST.get('passwd')
        user.phoneno = request.POST.get('phoneno')
        user.save()
        return render(request, 'dogbook/success.html')

    else:
        return render(request, 'dogbook/login_fail.html')

    # if 'id_check_btn' in request.POST:
    #     user = request.POST.get('username')
    #     return render(request, 'dogbook/popup.html')


def id_check(request):
    user = request.POST.get('username')
    con = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='wlgus7921', db='dogstagram_db', charset='utf8')
    cursor = con.cursor(pymysql.cursors.DictCursor)
    stmt = "SELECT username FROM dogbook_users WHERE username='{}'"
    stmt = stmt.format(user)
    cursor.execute(stmt)
    data = cursor.fetchall()
    # user = users.objects.get(username=username)
    if not data:
        # context = {'form': form, 'error': '이 아이디는 사용중입니다. 다른 아이디를 입력하세요.'}
        messages.success(request, f'This username can be used')
        return render(request, 'dogbook/id_success.html')
    else:
        messages.info(request, f'This username is already in use')
        return render(request, 'dogbook/id_fail.html')


def open_popup(request):
    return render(request, 'dogbook/popup.html')

def open_popup2(request, username):
    context = {'usr': username}
    return render(request, 'dogbook/popup.html', context)


def login(request):
    user = request.POST.get('username')
    passwd = request.POST.get('passwd')
    con = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='wlgus7921', db='dogstagram_db', charset='utf8')
    cursor = con.cursor(pymysql.cursors.DictCursor)
    stmt = "SELECT username FROM dogbook_users WHERE username='{}' and passwd='{}'"
    stmt = stmt.format(user, passwd)
    cursor.execute(stmt)
    data = cursor.fetchall()

    if not data:
        # context = get_object_or_404(users, username=username)
        return render(request, 'dogbook/login_fail.html')
    else:
        usr = get_object_or_404(users, username=user)
        context = {'thisuser': usr}
        return render(request, 'dogbook/login_success.html', context)


def profile(request, username):
    usr = get_object_or_404(users, username=username)
    imgs = Uploads2.objects.filter(author=username)
    context = {'thisuser': usr, 'usrimgs': imgs}
    return render(request, 'dogbook/profile.html', context)


def pet_register(request):
    return render(request, 'dogbook/pet_register.html')


def missing(request):
    return render(request, 'dogbook/practice.html')


def upload_page(request, username):
    usr = get_object_or_404(users, username=username)
    context = {'thisuser': usr}
    return render(request, 'dogbook/upload_page.html', context)


def upload(request):
    if request.method == "POST":
        # Fetching the form data
        contents = request.POST["content"]
        uploading_image = request.FILES.get("upload_image")
        author = request.POST['author']
        print('======================type', uploading_image, type(uploading_image))

        # Saving the information in the database
        post = Uploads2()
        post.author = author
        post.content = contents
        post.imagefile = uploading_image
        # chaeeun = Uploads2(
        #     content = contents,
        #     author = author,
        #     imagefile = uploading_image
        # )
        print('==2222=========================', post.author, post.content, post.upload_date, post.imagefile)
        post.save()

    return HttpResponseRedirect(reverse('dogbook:profile', args=(author,)))

dogbook/templates/dogbook/id_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
아이디 사용중
</body>
</html>

dogbook/templates/dogbook/id_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
아이디 사용 가능
</body>
</html>

dogbook/templates/dogbook/login_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
로그인 실패!!
</body>
</html>

dogbook/templates/dogbook/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
로그인 성공
<form action="/dogbook/{{ thisuser.username }}/" method="POST">
    {% csrf_token %}
    <input type="hidden" name="username" value="{{ thisuser.username }}">
    <button type="submit">내 프로필 가기</button>
</form>
</body>
</html>

dogbook/templates/dogbook/missing.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Album example · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">

    <!-- Bootstrap core CSS -->
<link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>

    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">목격</h1>
        <p class="lead text-muted" id="status">로딩중...</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 g-3">


        <div class="col">
          <!-- width height -->
          

          <div class="card shadow-sm" width="50%">
            <!-- <img id="imageSrc" src="base.jpg"/> -->
            
            <img id="img" src="/static/img/base.jpg">
            <input class="btn btn-sm btn-outline-secondary" id="input" type="file"  name="file" />
            <!-- <input id="input" type="file" name="file" /> -->
            <h1 id='result'></h1>

            <div class="card-body">
              <p class="card-text">목격자</p>



              <!-- <input class="btn btn-sm btn-outline-secondary" type="file" id="fileInput" name="file" /> -->

              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>


    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.11.0/dist/tf.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet@2.1.0"> </script>

    <script type="text/javascript">
        let imgElement = document.getElementById('imageSrc');
        let inputElement = document.getElementById('fileInput');
        inputElement.addEventListener('change', (e) => {
        imgElement.src = URL.createObjectURL(e.target.files[0]);
        }, false);
        imgElement.onload = function() {
            let mat = cv.imread(imgElement);
            cv.imshow('canvasOutput', mat);
            mat.delete();
          };
          function onOpenCvReady() {
            document.getElementById('status').innerHTML = '';
          }
    </script>

    <script async src="/static/js/opencv.js" onload="onOpenCvReady();" type="text/javascript"></script>
    <script>
      const img = document.getElementById('img');


      mobilenet.load().then(model => {

          function run() {
              model.classify(img).then(predictions => {

                // <!-- 품종 결과값 -->
                  console.log('Predictions: ', predictions);
                  result.innerHTML = predictions[0].className + ' ' + parseInt(predictions[0].probability * 100) + '%';
              });
          }
          img.src = "/static/img/base.jpg";
          input.addEventListener('change', (e) => {
              img.src = URL.createObjectURL(e.target.files[0]);
          }, false);

          img.onload = function () {
              run();
          };

      });



  </script>
    

  </body>
</html>

dogbook/templates/dogbook/pet_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>반려동물 등록</title>
</head>
<body>
    반려동물 등록
</body>
</html>

dogbook/templates/dogbook/popup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>중복 아이디 체크</title>
</head>
<body>
    <div class="col-5" style="text-align:center;">
      <form action="idcheck/" method="POST">
      {% csrf_token %}
      <label for="username" class="form-label">아이디</label>
      <div class="input-group has-validation">
        <span class="input-group-text">@</span>
        <input type="text" class="form-control" name="username" value="{{ usr }}" required>
          &nbsp
        <div class="col-2">
          <button class="w-50 btn btn-secondary btn-sm" type="submit" id="id_check_btn" onclick="">중복 확인</button>
        </div>
      </form>
      </div>
    </div>
</body>
</html>

dogbook/templates/dogbook/practice.html
<!DOCTYPE html>
<head>
<meta charset="UTF-8">
<title>Upload Images</title>
</head>
<body>

<h1>Image Uploader</h1>
<form enctype="multipart/form-data" method="POST" action="">
    {% csrf_token %}
    <input class="btn btn-sm btn-outline-secondary" id="input" type="file" name="file" />
    {{ form.as_p }}
    <input type="submit" value="Upload"/>
</form>

<br><br>
<img src='{{ MEDIA_URL }}{{ imagefile }}' id="img" width=50% />
<br><br>
<script>
  const img = document.getElementById('img');
    input.addEventListener('change', (e) => {
        img.src = URL.createObjectURL(e.target.files[0]);
    }, false);

</script>
</p>

</body>
</html>

dogbook/templates/dogbook/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>프로필 페이지</title>
</head>
<body>
    <script>
        console.log("====", {{ thisuser.username }})
    </script>

    {{ thisuser.username }}의 프로필 페이지 ~~
    <a href="{% url 'dogbook:pet_register' %}">
        <input type="button" value="내 반려동물 등록하기">
    </a>
    <a href="{% url 'dogbook:missing' %}">
        <input type="button" value="실종신고 하기">
    </a>
    <form action="{% url 'dogbook:upload_page' thisuser.username %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="username" value="{{ thisuser.username }}">
        <input type="submit" value="사진 업로드">
    </form>

    <table>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>File Path</th>
            <th>Upload Date & Time</th>
        </tr>
        {% for file in usrimgs %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.name }}</td>
                <td>{{ file.imagefile.url }}</td>
                <td>{{ file.upload_date }}</td>
                <div >
                <td><img src="{{ file.imagefile.url }}" id="hihi" /></td></div>
            </tr>
        {% endfor %}
    </table>

</body>
</html>

dogbook/templates/dogbook/register.html
<!doctype html>
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>회원가입 하기</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/checkout/">

    <!-- Bootstrap core CSS -->
<link href="/static/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

<script>
    function showPopup() {
        let usr = document.getElementById("username").value
        window.open(`popup/${usr}`, "a", "width=400, height=300, left=100, top=50");
    }
</script>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      /* The message box is shown when the user clicks on the password field */
        #message {
          display:none;
          background: #f1f1f1;
          color: #000;
          position: relative;
          padding: 20px;
          margin-top: 10px;
        }

        #message p {
          padding: 10px 35px;
          font-size: 18px;
        }

        /* Add a green text color and a checkmark when the requirements are right */
        .valid {
          color: green;
        }

        /* Add a red text color and an "x" icon when the requirements are wrong */
        .invalid {
          color: red;
        }

    </style>

    
    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
  </head>
  <body class="bg-light">
    
<div class="container">
  <main>
    <div class="py-5 text-center">
      <h2>회원가입 하기</h2>
      <p class="lead">Petstagram에 오신 것을 환영합니다</p>
    </div>
        <h4 class="mb-3">정보 입력</h4>
        <form action="/dogbook/create_process/" method="POST">
          {% csrf_token %}
          <div class="row g-3">
            <div class="col-sm-6">
              <label for="full_name" class="form-label">이름</label>
              <input type="text" class="form-control" name="full_name" placeholder="" value="" required>
              <div class="invalid-feedback">
                Valid name is required.
              </div>
            </div>

            <div class="col-10">
              <label for="username" class="form-label">아이디</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
              <div class="invalid-feedback">
                  Your username is required.
              </div>
                  &nbsp
                <div class="col-2">
                  <button class="w-50 btn btn-primary btn-sm" type="button" id="id_check_btn" name="id_check_btn" onclick="showPopup()">아이디 체크</button>
                </div>
              </div>
            </div>

            <div class="col-12">
              <label for="email" class="form-label">이메일</label>
              <input type="email" class="form-control" name="email" placeholder="you@example.com" required>
              <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
              </div>
            </div>

            <div class="col-12">
              <label for="phoneno" class="form-label">전화번호 <span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" name="phoneno" placeholder="000-0000-0000">
            </div>

            <div class="col-12">
              <label for="passwd" class="form-label">비밀번호</label>
              <input type="password" class="form-control" name="passwd" id="passwd" placeholder="비밀번호" required>
            </div>

            <div id="message">
              <p id="vali" class="invalid">비밀번호는 영어 소문자/대문자, 숫자를 포함해 8자 이상이어야 합니다.</p>
            </div>

            <script>
                let myInput = document.getElementById("passwd");
                let vali = document.getElementById("vali")
                let btn = document.getElementById("register")

                // When the user clicks on the password field, show the message box
                myInput.onfocus = function() {
                  document.getElementById("message").style.display = "block";
                }

                // When the user clicks outside of the password field, hide the message box
                myInput.onblur = function() {
                  document.getElementById("message").style.display = "none";
                }

                // When the user starts to type something inside the password field
                myInput.onkeyup = function() {
                  // Validate lowercase letters
                  var lowerCaseLetters = /[a-z]/g;
                  var boo1 = 0
                  if(myInput.value.match(lowerCaseLetters)) {
                    boo1 = 1
                  } else {
                    boo1 = 0
                  }

                  // Validate capital letters
                  var upperCaseLetters = /[A-Z]/g;
                  var boo2 = 0
                  if(myInput.value.match(upperCaseLetters)) {
                    boo2 = 1
                  } else {
                    boo2 = 0
                  }

                  // Validate numbers
                  var numbers = /[0-9]/g;
                  var boo3 = 0
                  if(myInput.value.match(numbers)) {
                    boo3 = 1
                  } else {
                    boo3 = 0
                  }

                  // Validate length
                  var boo4 = 0
                  if(myInput.value.length >= 8) {
                    boo4 = 1
                  } else {
                    boo4 = 0
                  }

                  if (boo1 == 1 & boo2 == 1 & boo3 == 1 & boo4 == 1) {
                      vali.classList.remove('invalid')
                      vali.classList.add('valid')
                  }
                  else {
                      vali.classList.remove('valid')
                      vali.classList.add('invalid')
                  }

                }
            </script>

            <div class="col-md-5">
              <label for="country" class="form-label">반려동물 종</label>
              <select class="form-select" id="country" required>
                <option value="">Choose...</option>
                <option>강아지</option>
                <option>고양이</option>
                <option>그 외</option>
              </select>
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>
          </div>


          <br>
{#        <script>#}
{#            btn.addEventListener("change", stateChange)#}
{##}
{#            function stateChange() {#}
{#                if (vali.className == 'valid') {#}
{#                    btn.disabled = false#}
{#                }#}
{#                else {#}
{#                    btn.disabled = true#}
{#                }#}
{#            }#}
{#        </script>#}

          <input class="w-100 btn btn-primary btn-lg" type="submit" name="register" id="register" value="회원가입 하기">

        </form>
  </main>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2022- petstagram</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>


    <script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

      <script src="form-validation.js"></script>
  </body>
</html>

dogbook/templates/dogbook/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>가입을 축하합니다</title>
</head>
<body>
Petstagram 가입을 축하합니다
<a href="/"><input type="button" value="로그인하기"> </a>
</body>
</html>

dogbook/templates/dogbook/upload_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django File Upload</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');

        * {
            font-family: "Roboto";
        }

        body {
            background-color: #F5F5F5;
        }

        form {
            background-color: #FFFFFF;
            padding: 25px;
        }

        table {
            width: 100%;
            text-align: center;
            margin-top: 25px;
            padding: 25px;
            background-color: #FFFFFF;
        }

        table tr td {
            padding-top: 15px;
        }
    </style>
</head>
<body>
    <form action="{% url 'dogbook:uploading' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="author" value={{ thisuser.username }}>
        <input type="text" name="content" placeholder="글 내용">
        <input type="file" name="upload_image">
        <input type="submit" value="Upload">
    </form>
{#    <script>#}
{#        let aa = {{ thisuser.username }}#}
{#        console.log('====='+ aa)#}
{#    </script>#}

</body>
</html>